<?php

return array (
  'APP_SECRET' => NULL,
  'AWS_ACCESS_KEY_ID' => NULL,
  'AWS_SECRET_ACCESS_KEY' => NULL,
  'DATABASE_URL' => NULL,
  'KLAVIYO_PRIVATE_KEY' => NULL,
  'KLAVIYO_PUBLIC_KEY' => NULL,
  'LOCK_DSN' => NULL,
  'REDIS_URL' => NULL,
);
