version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
    - source: .
      destination: /app
    - source: ./deploy/app.nginx.conf
      destination: /etc/nginx/sites-enabled/app.conf
permissions:
    - object: /app
      pattern: "**"
      owner: www-data
      group: www-data
      type:
          - file
          - directory
hooks:
    #ApplicationStop:
    #    - location: scripts/stop-workers.sh
    #      runas: www-data
    BeforeInstall:
        #- location: scripts/migtaions.sh
        #  timeout: 300
        - location: scripts/install-deps.sh
          timeout: 300
    #AfterInstall:
    #    - location: scripts/install-deps.sh
    #      timeout: 300
    #ApplicationStart:
    #    - location: scripts/start-workers.sh
    #      runas: www-data
    ValidateService:
        - location: scripts/cleanup.sh
