version: 0.0
os: linux
files:
    - source: .
      destination: /app
file_exists_behavior: OVERWRITE
permissions:
    - object: /app
      pattern: "**"
      owner: www-data
      group: www-data
      type:
          - file
          - directory

#hooks:
#    BeforeInstall:
#        - location: scripts/migtaions.sh
#        - location: scripts/stop-workers.sh
#    AfterInstall:
#        - location: scripts/after-install.sh
#    ApplicationStart:
#        - location: scripts/application-start.sh
#    ValidateService:
#        - location: scripts/validate-service.sh
