# @see https://docs.docker.com/compose/compose-file/
version: 3
services:
    # @see https://hub.docker.com/_/postgres/
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app
        #ports:
        #    - "5432:5432"
        networks:
            - database
        volumes:
            - ./var/data:/var/lib/postgresql/data:cached

    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - .:/app:cached
        networks:
            - database
            - php

    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm
        networks:
            - php
        volumes:
            - .:/app:cached

    # @see https://hub.docker.com/_/redis/
    redis:
        image: redis
        networks:
            - php

networks:
    database:
    php:
